stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/interim
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/interim
    - src/model/model_building.py
    outs:
    - log_model.pkl
    - tfidf_vectorizer.pkl
  model_eval:
    cmd: python src/model/model_evaluation.py
    deps:
    - data/interim
    - log_model.pkl
    - tfidf_vectorizer.pkl
    - src/model/model_evaluation.py
    outs:
    - experiment_info.json
