name : CICD Pipeline 

on:
  push:
    branches:
      - master

jobs:
  model_deployment:
    runs-on : ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
        
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name : Install dependencies
        run : |
          pip install -r requirements.txt
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
        
      - name : Run DVC pipeline
        run : |
          dvc repro

      - name : Push DVC-tracked to remote
        run : |
          dvc push 
      
      - name : Configure git 
        run : |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name : Add Changes to git 
        run : |
          git add . 

      - name : Commit to github 
        if: ${{ github.actor == 'github-actions[bot]' }}
        run : | 
          git commit -m "Auto commit of dvc outputs and updated code" 

      - name : Push to github
        if: ${{ github.actor == 'github-actions[bot]' }}
        env : 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run : |
          git push origin {{ github.ref_name }}

      - name : install pytest
        run : |
          pip install pytest

      - name : Load model test 
        run : | 
          pytest scripts/test_model_load.py

      - name : test_signature 
        run : | 
          pytest scripts/test_signature_load.py

      - name : test model performance 
        run : | 
          pytest scripts/test_model_performance.py

      - name : Test Fast api endpoints
        run : |
          pytest scripts/test_flask_api.py

      - name : Promote model to production 
        if: success()
        run : |
          python scripts/promote_model.py
      